apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  labels:
    {{- include "deps-frontend.labels" . | nindent 4 }}
data:
  API_GATEWAY_URL: {{ .Values.frontend_settings.api_gateway_url | quote }}
  BACKEND_URL: {{ .Values.frontend_settings.backend_url | quote }}
  COMPARISON_URL: {{ .Values.frontend_settings.comparison_url | quote }}
  FILE_STORAGE_URL: {{ .Values.frontend_settings.file_storage_url | quote }}
  IAM_URL: {{ .Values.frontend_settings.iam_url | quote }}
  OCR_URL: {{ .Values.frontend_settings.ocr_url | quote }}
  OMR_URL: {{ .Values.frontend_settings.omr_url | quote }}
  PREPROCESS_URL: {{ .Values.frontend_settings.preprocess_url | quote }}
  TABLES_URL: {{ .Values.frontend_settings.tables_url | quote }}
  TEMPLATE_URL: {{ .Values.frontend_settings.template_url | quote }}
  WORKFLOW_MANAGER_URL: {{ .Values.frontend_settings.workflow_manager_url | quote }}
  OUTPUT_EXPORTING_URL: {{ .Values.frontend_settings.output_exporting_url | quote }}
  IMAGE_PREPROCESS_URL: {{ .Values.frontend_settings.image_preprocess_url | quote }}
  DOCUMENT_TYPE_URL: {{ .Values.frontend_settings.document_type_url | quote }}
  EXTRACTION_URL: {{ .Values.frontend_settings.extraction_url | quote }}
  UNIFIER_URL: {{ .Values.frontend_settings.unifier_url | quote }}
  RESULT_EXPORTING_URL: {{ .Values.frontend_settings.result_exporting_url | quote }}
  PROTOTYPE_URL: {{ .Values.frontend_settings.prototype_url | quote }}
  NER_URL: {{ .Values.frontend_settings.ner_url | quote }}
  PROMPTER_URL: {{ .Values.frontend_settings.prompter_url | quote }}
  BASE_API_URL: {{ .Values.frontend_settings.base_api_url | quote }}
  AGENTIC_AI_URL: {{ .Values.frontend_settings.agentic_ai_url | quote }}
  FALLBACK_LANG: {{ .Values.frontend_settings.FALLBACK_LANG | quote }}
  FEATURE_CONFIDENCE_LEVEL_VIEW: {{ .Values.frontend_settings.FEATURE_CONFIDENCE_LEVEL_VIEW | quote }}
  FEATURE_DATA_EXTRACTION: {{ .Values.frontend_settings.FEATURE_DATA_EXTRACTION | quote }}
  FEATURE_DOCUMENT_CHANGE_TYPE: {{ .Values.frontend_settings.FEATURE_DOCUMENT_CHANGE_TYPE | quote }}
  FEATURE_DOCUMENT_DELETE: {{ .Values.frontend_settings.FEATURE_DOCUMENT_DELETE | quote }}
  FEATURE_DOCUMENT_UPLOAD: {{ .Values.frontend_settings.FEATURE_DOCUMENT_UPLOAD | quote }}
  FEATURE_ENTITIES_UPLOAD: {{ .Values.frontend_settings.FEATURE_ENTITIES_UPLOAD | quote }}
  FEATURE_INVITE_OPTIONS: {{ .Values.frontend_settings.FEATURE_INVITE_OPTIONS | quote }}
  FEATURE_LABELING_TOOL: {{ .Values.frontend_settings.FEATURE_LABELING_TOOL | quote }}
  FEATURE_LIST_EDITING_MODE: {{ .Values.frontend_settings.FEATURE_LIST_EDITING_MODE | quote }}
  FEATURE_MACHINE_LEARNING_MODELS: {{ .Values.frontend_settings.FEATURE_MACHINE_LEARNING_MODELS | quote }}
  FEATURE_RETRY_PREVIOUS_STEP: {{ .Values.frontend_settings.FEATURE_RETRY_PREVIOUS_STEP | quote }}
  FEATURE_BULK_RETRY_PREVIOUS_STEP: {{ .Values.frontend_settings.FEATURE_BULK_RETRY_PREVIOUS_STEP | quote }}
  FEATURE_RUN_PIPELINE: {{ .Values.frontend_settings.FEATURE_RUN_PIPELINE | quote }}
  ELASTIC_ENVIRONMENT: {{ .Values.frontend_settings.ELASTIC_ENVIRONMENT | quote }}
  ELASTIC_SERVICE_NAME: {{ .Values.frontend_settings.ELASTIC_SERVICE_NAME | quote }}
  ELASTIC_PROJECT_CODE: {{ .Values.frontend_settings.ELASTIC_PROJECT_CODE | quote }}
  FEATURE_TABLE_DETECTION: {{ .Values.frontend_settings.FEATURE_TABLE_DETECTION | quote }}
  FEATURE_USER_MANAGEMENT: {{ .Values.frontend_settings.FEATURE_USER_MANAGEMENT | quote }}
  FEATURE_INVITE_BY_MAIL: {{ .Values.frontend_settings.FEATURE_INVITE_BY_MAIL | quote }}
  FEATURE_COPY_INVITE: {{ .Values.frontend_settings.FEATURE_COPY_INVITE | quote }}
  FEATURE_PAGINATED_TABLES: {{ .Values.frontend_settings.FEATURE_PAGINATED_TABLES | quote }}
  FEATURE_CONFIGURABLE_CONFIDENCE_LEVEL: {{ .Values.frontend_settings.FEATURE_CONFIGURABLE_CONFIDENCE_LEVEL | quote }}
  FEATURE_HIDE_LOW_CONFIDENCE_DUE_TO_VALIDATION_ERRORS: {{ .Values.frontend_settings.FEATURE_HIDE_LOW_CONFIDENCE_DUE_TO_VALIDATION_ERRORS | quote }}
  FEATURE_SHOW_NOT_APPLICABLE_CONFIDENCE: {{ .Values.frontend_settings.FEATURE_SHOW_NOT_APPLICABLE_CONFIDENCE | quote }}
  FEATURE_COLLAPSIBLE_SELECTED_CELLS: {{ .Values.frontend_settings.FEATURE_COLLAPSIBLE_SELECTED_CELLS | quote }}
  FEATURE_MANAGE_TEMPLATE_VERSIONS: {{ .Values.frontend_settings.FEATURE_MANAGE_TEMPLATE_VERSIONS | quote }}
  FEATURE_TRIAL_VERSION: {{ .Values.frontend_settings.FEATURE_TRIAL_VERSION | quote }}
  FEATURE_UI_SETTINGS: {{ .Values.frontend_settings.FEATURE_UI_SETTINGS | quote }}
  FEATURE_OIDC_LOG_LEVEL: {{ .Values.frontend_settings.FEATURE_OIDC_LOG_LEVEL | quote }}
  FEATURE_SERVER_SENT_EVENTS: {{ .Values.frontend_settings.FEATURE_SERVER_SENT_EVENTS | quote }}
  FEATURE_OCR_INTERSECTION_ALGORITHM: {{ .Values.frontend_settings.FEATURE_OCR_INTERSECTION_ALGORITHM | quote }}
  FEATURE_OCR_INTERSECTION_ALGORITHM_THRESHOLD: {{ .Values.frontend_settings.FEATURE_OCR_INTERSECTION_ALGORITHM_THRESHOLD | quote }}
  FEATURE_AUTO_LABELING: {{ .Values.frontend_settings.FEATURE_AUTO_LABELING | quote }}
  FEATURE_DASHBOARD: {{ .Values.frontend_settings.FEATURE_DASHBOARD | quote }}
  FEATURE_OUTPUT_PROFILES: {{ .Values.frontend_settings.FEATURE_OUTPUT_PROFILES | quote }}
  FEATURE_LLM_EXTRACTORS: {{ .Values.frontend_settings.FEATURE_LLM_EXTRACTORS | quote }}
  FEATURE_HIDDEN_ENGINES: {{ .Values.frontend_settings.FEATURE_HIDDEN_ENGINES | quote }}
  FEATURE_HIDDEN_LLM_PROVIDERS: {{ .Values.frontend_settings.FEATURE_HIDDEN_LLM_PROVIDERS | quote }}
  FEATURE_PROTOTYPES: {{ .Values.frontend_settings.FEATURE_PROTOTYPES | quote }}
  FEATURE_AI_PROMPTED_EXTRACTORS: {{ .Values.frontend_settings.FEATURE_AI_PROMPTED_EXTRACTORS | quote }}
  FEATURE_PROTOTYPE_REFERENCE_LAYOUT: {{ .Values.frontend_settings.FEATURE_PROTOTYPE_REFERENCE_LAYOUT | quote }}
  FEATURE_DOCUMENT_LAYOUT_EDITING: {{ .Values.frontend_settings.FEATURE_DOCUMENT_LAYOUT_EDITING | quote }}
  FEATURE_FILE_LAYOUT_EDITING: {{ .Values.frontend_settings.FEATURE_FILE_LAYOUT_EDITING | quote }}
  FEATURE_GEN_AI_CHAT: {{ .Values.frontend_settings.FEATURE_GEN_AI_CHAT | quote }}
  FEATURE_AGENTIC_DOCUMENT_PROCESSING: {{ .Values.frontend_settings.FEATURE_AGENTIC_DOCUMENT_PROCESSING | quote }}
  FEATURE_GEN_AI_KEY_VALUE_FIELDS: {{ .Values.frontend_settings.FEATURE_GEN_AI_KEY_VALUE_FIELDS | quote }}
  FEATURE_SEQUENTIAL_PROTOTYPE_REQUESTS: {{ .Values.frontend_settings.FEATURE_SEQUENTIAL_PROTOTYPE_REQUESTS | quote }}
  FEATURE_TEMPLATES: {{ .Values.frontend_settings.FEATURE_TEMPLATES | quote }}
  FEATURE_DOCUMENT_LAYOUT: {{ .Values.frontend_settings.FEATURE_DOCUMENT_LAYOUT | quote }}
  FEATURE_FILL_CANVAS_POLYGONS: {{ .Values.frontend_settings.FEATURE_FILL_CANVAS_POLYGONS | quote }}
  FEATURE_MULTIFILE_SESSION_UPLOAD: {{ .Values.frontend_settings.FEATURE_MULTIFILE_SESSION_UPLOAD | quote }}
  FEATURE_SCALE_TO_POINT: {{ .Values.frontend_settings.FEATURE_SCALE_TO_POINT | quote }}
  FEATURE_HIDE_LEGACY: {{ .Values.frontend_settings.FEATURE_HIDE_LEGACY | quote }}
  FEATURE_FILE_CACHE: {{ .Values.frontend_settings.FEATURE_FILE_CACHE | quote }}
  FEATURE_PDF_VIEWER: {{ .Values.frontend_settings.FEATURE_PDF_VIEWER | quote }}
  FEATURE_PER_FIELD_VALIDATION: {{ .Values.frontend_settings.FEATURE_PER_FIELD_VALIDATION | quote }}
  FEATURE_FIELDS_DISPLAY_MODE: {{ .Values.frontend_settings.FEATURE_FIELDS_DISPLAY_MODE | quote }}
  FEATURE_ENRICHMENT: {{ .Values.frontend_settings.FEATURE_ENRICHMENT | quote }}
  FEATURE_LLM_DATA_EXTRACTION: {{ .Values.frontend_settings.FEATURE_LLM_DATA_EXTRACTION | quote }}
  FEATURE_CONSOLIDATED_DOCUMENT_TYPE_FIELDS: {{ .Values.frontend_settings.FEATURE_CONSOLIDATED_DOCUMENT_TYPE_FIELDS | quote }}
  FEATURE_DOCUMENT_TYPES_GROUPS: {{ .Values.frontend_settings.FEATURE_DOCUMENT_TYPES_GROUPS | quote }}
  FEATURE_FILES_BATCH: {{ .Values.frontend_settings.FEATURE_FILES_BATCH | quote }}
  FEATURE_AZURE_CLOUD_NATIVE_EXTRACTOR: {{ .Values.frontend_settings.FEATURE_AZURE_CLOUD_NATIVE_EXTRACTOR | quote }}
  FEATURE_PDF_SPLITTING: {{ .Values.frontend_settings.FEATURE_PDF_SPLITTING | quote }}
  FEATURE_ASSIGN_DOCUMENT_TYPE_TO_FILE: {{ .Values.frontend_settings.FEATURE_ASSIGN_DOCUMENT_TYPE_TO_FILE | quote }}
  DEFAULT_MAX_CELL_CONTENT_LENGTH: {{ .Values.frontend_settings.DEFAULT_MAX_CELL_CONTENT_LENGTH | quote }}
  DEFAULT_CONFIDENCE_LEVEL_TO_DISPLAY: {{ .Values.frontend_settings.DEFAULT_CONFIDENCE_LEVEL_TO_DISPLAY | quote }}
  MAX_FILE_SIZE_MB: {{ .Values.frontend_settings.MAX_FILE_SIZE_MB | quote }}
  REQUEST_TIMEOUT: {{ .Values.frontend_settings.REQUEST_TIMEOUT | quote }}
  MAX_PROTOTYPE_REFERENCE_LAYOUT_SIZE_MB: {{ .Values.frontend_settings.MAX_PROTOTYPE_REFERENCE_LAYOUT_SIZE_MB | quote }}
  WTF_CSRF_ENABLED: {{ .Values.frontend_settings.WTF_CSRF_ENABLED | quote }}
  AUTH_SCOPE: {{ .Values.frontend_settings.AUTH_SCOPE | quote }}
  GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL: {{ .Values.frontend_settings.GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL | quote }}
  ONE_DRIVE_SERVICE_ACCOUNT_EMAIL: {{ .Values.frontend_settings.ONE_DRIVE_SERVICE_ACCOUNT_EMAIL | quote }}
  FEATURE_CLASSIFIER: {{ .Values.frontend_settings.FEATURE_CLASSIFIER | quote }}
  FEATURE_OMR_AREA: {{ .Values.frontend_settings.FEATURE_OMR_AREA | quote }}
  FEATURE_FILES: {{ .Values.frontend_settings.FEATURE_FILES | quote }}
  FEATURE_DOCUMENT_TYPE_IMPORT_EXPORT: {{ .Values.frontend_settings.FEATURE_DOCUMENT_TYPE_IMPORT_EXPORT | quote }}
  FEATURE_SERVICE_AVAILABILITY_CHECK: {{ .Values.frontend_settings.FEATURE_SERVICE_AVAILABILITY_CHECK | quote }}
  MENU_INTEGRATION_SCRIPT_URI: {{ .Values.frontend_settings.MENU_INTEGRATION_SCRIPT_URI | quote }}
  FEATURE_VALIDATION_BUSINESS_RULES: {{ .Values.frontend_settings.FEATURE_VALIDATION_BUSINESS_RULES | quote }}
  FEATURE_PROMPT_CALIBRATION_STUDIO: {{ .Values.frontend_settings.FEATURE_PROMPT_CALIBRATION_STUDIO | quote }}
  FEATURE_PROMPT_CALIBRATION_STUDIO_MODEL: {{ .Values.frontend_settings.FEATURE_PROMPT_CALIBRATION_STUDIO_MODEL | quote }}
  FEATURE_PROMPT_CALIBRATION_STUDIO_TOP_P: {{ .Values.frontend_settings.FEATURE_PROMPT_CALIBRATION_STUDIO_TOP_P | quote }}
  FEATURE_PROMPT_CALIBRATION_STUDIO_TEMPERATURE: {{ .Values.frontend_settings.FEATURE_PROMPT_CALIBRATION_STUDIO_TEMPERATURE | quote }}
  FEATURE_PROMPT_CALIBRATION_STUDIO_GROUPING_FACTOR: {{ .Values.frontend_settings.FEATURE_PROMPT_CALIBRATION_STUDIO_GROUPING_FACTOR | quote }}
