{{- if .Values.vault_settings.aws_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  provider: aws
  parameters:
    region: {{ .Values.vault_settings.aws_secret_manager_region }}
    objects: |
      - objectName: "auth-type"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-realm"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-base-url"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "auth-client-id"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "support-email"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "elastic-server-url"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "google-drive-client-id"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "one-drive-client-id"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "mfe-comparison-url"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
      - objectName: "google-drive-api-key"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_frontend.secretName }}
      type: Opaque
      data:
        - objectName: "google-drive-api-key"
          key: google-drive-api-key
        - objectName: "auth-type"
          key: auth-type
        - objectName: "auth-realm"
          key: "auth-realm"
        - objectName: "auth-base-url"
          key: auth-base-url
        - objectName: "auth-client-id"
          key: auth-client-id
        - objectName: "support-email"
          key: support-email
        - objectName: "elastic-server-url"
          key: elastic-server-url
        - objectName: "google-drive-client-id"
          key: google-drive-client-id
        - objectName: "one-drive-client-id"
          key: one-drive-client-id
        - objectName: "mfe-comparison-url"
          key: mfe-comparison-url
{{- end }}