{{- if .Values.vault_settings.azure_key_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: azure
  secretObjects:
  - data:
    - key: auth-type
      objectName: auth-type
    - key: auth-realm
      objectName: auth-realm
    - key: auth-base-url
      objectName: auth-base-url
    - key: auth-client-id
      objectName: auth-client-id
    - key: support-email
      objectName: support-email
    - key: elastic-server-url
      objectName: elastic-server-url
    - key: google-drive-client-id
      objectName: google-drive-client-id
    - key: one-drive-client-id
      objectName: one-drive-client-id
    - key: mfe-comparison-url
      objectName: mfe-comparison-url
    secretName: {{ .Values.secrets.deps_frontend.secretName }}
    type: Opaque
  parameters:
    keyvaultName: {{ .Values.azure_kv_settings.keyvaultName }}
    tenantId: {{ .Values.azure_kv_settings.tenantId }}
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure_kv_settings.userAssignedIdentityID }}
    resourceGroup:  {{ .Values.azure_kv_settings.resourceGroup }}
    subscriptionId: {{ .Values.azure_kv_settings.subscriptionId }}
    objects: |
      array:
        - |
          objectName: "auth-type"
          objectType: secret

        - |
          objectName: "auth-realm"
          objectType: secret

        - |
          objectName: "auth-base-url"
          objectType: secret

        - |
          objectName: "auth-client-id"
          objectType: secret

        - |
          objectName: "support-email"
          objectType: secret

        - |
          objectName: "elastic-server-url"
          objectType: secret

        - |
          objectName: "google-drive-client-id"
          objectType: secret

        - |
          objectName: "one-drive-client-id"
          objectType: secret

        - |
          objectName: "mfe-comparison-url"
          objectType: secret
{{- end }}
