{{- if .Values.vault_settings.hashicorp_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: vault
  secretObjects:
  - data:
    - key: file-storage-external-url
      objectName: file-storage-external-url
    - key: backend-url
      objectName: backend-url
    - key: tables-url
      objectName: tables-url
    - key: preprocess-url
      objectName: preprocess-url
    - key: ocr-url
      objectName: ocr-url
    - key: file-storage-url
      objectName: file-storage-url
    - key: omr-url
      objectName: omr-url
    - key: iam-url
      objectName: iam-url
    - key: template-url
      objectName: template-url
    - key: auth-base-url
      objectName: auth-base-url
    - key: auth-client-id
      objectName: auth-client-id
    - key: validation-url
      objectName: validation-url
    - key: support-email
      objectName: support-email
    - key: workflow-manager-url
      objectName: workflow-manager-url
    - key: api-gateway-url
      objectName: api-gateway-url
    - key: elastic-server-url
      objectName: elastic-server-url
    - key: auth-realm
      objectName: auth-realm
    - key: auth-type
      objectName: auth-type
    - key: google-drive-client-id
      objectName: google-drive-client-id
    - key: google-drive-api-key
      objectName: google-drive-api-key
    - key: one-drive-client-id
      objectName: one-drive-client-id
    secretName: {{ .Values.secrets.deps_frontend.secretName }}
    type: Opaque
  parameters:
    roleName: {{ .Values.csi.roleName }}
    vaultAddress: "localhost:8200"
    vaultNamespace: "bss-dev/epm-deps"
    vaultSkipTLSVerify: "true"
    #vaultCACertPath: /csi/epam_issuing.pem
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    objects: |
      - objectName: "api-gateway-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "api-gateway-url"

      - objectName: "file-storage-external-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "file-storage-external-url"

      - objectName: "backend-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "backend-url"

      - objectName: "tables-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "tables-url"

      - objectName: "preprocess-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "preprocess-url"

      - objectName: "ocr-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "ocr-url"

      - objectName: "file-storage-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "file-storage-url"

      - objectName: "omr-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "omr-url"

      - objectName: "iam-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "iam-url"

      - objectName: "template-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "template-url"

      - objectName: "auth-base-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "auth-base-url"

      - objectName: "auth-client-id"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "auth-client-id"

      - objectName: "validation-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "validation-url"

      - objectName: "support-email"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "support-email"

      - objectName: "workflow-manager-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "workflow-manager-url"

      - objectName: "elastic-server-url"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "elastic-server-url"

      - objectName: "auth-realm"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "auth-realm"

      - objectName: "auth-type"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "auth-type"

      - objectName: "google-drive-client-id"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "google-drive-client-id"

      - objectName: "google-drive-api-key"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "google-drive-api-key"

      - objectName: "one-drive-client-id"
        secretPath: "{{ .Values.csi.vault_namespace }}/data/deps-frontend/frontend-secret"
        secretKey: "one-drive-client-id"
{{- end }}
