{{- if .Values.vault_settings.gcp_secret_manager }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/auth-type/versions/latest" 
        fileName: "auth-type"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/auth-realm/versions/latest" 
        fileName: "auth-realm"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-auth-base-url/versions/latest" 
        fileName: "auth-base-url"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-auth-client-id/versions/latest" 
        fileName: "auth-client-id"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-auth-client-secret/versions/latest" 
        fileName: "auth-client-secret"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/support-email/versions/latest" 
        fileName: "support-email"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/elastic-server-url/versions/latest" 
        fileName: "elastic-server-url"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-google-drive-api-key/versions/latest" 
        fileName: "google-drive-api-key"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-google-drive-client-id/versions/latest" 
        fileName: "google-drive-client-id"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/{{ .Values.env }}-one-drive-client-id/versions/latest" 
        fileName: "one-drive-client-id"
      - resourceName: "projects/{{ .Values.secret_project_id.id }}/secrets/mfe-comparison-url/versions/latest" 
        fileName: "mfe-comparison-url"
  secretObjects:
    - secretName: {{ .Values.secrets.deps_frontend.secretName }}
      type: Opaque
      data:
      - objectName: "mfe-comparison-url"
        key: mfe-comparison-url
      - objectName: "one-drive-client-id"
        key: one-drive-client-id
      - objectName: "google-drive-client-id"
        key: google-drive-client-id
      - objectName: "google-drive-api-key"
        key: google-drive-api-key
      - objectName: "elastic-server-url"
        key: elastic-server-url
      - objectName: "support-email"
        key: support-email
      - objectName: "auth-client-secret"
        key: auth-client-secret
      - objectName: "auth-client-id"
        key: auth-client-id
      - objectName: "auth-base-url"
        key: auth-base-url
      - objectName: "auth-realm"
        key: auth-realm
      - objectName: "auth-type"
        key: auth-type
{{- end }}
