apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "deps-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "deps-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deps-frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.podSecurityContext.runAsNonRoot }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if or .Values.vault_settings.hashicorp_vault .Values.vault_settings.gcp_secret_manager .Values.vault_settings.aws_secret_manager }}
      serviceAccountName: {{ .Values.service_account.serviceAccountName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ .Values.registry }}{{ .Values.image.path }}:{{ .Values.image.tag | default "latest" }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
          - configMapRef:
              name: frontend-configmap
              optional: false
          env:
          {{- if .Values.vault_settings.enabled }}
          {{- toYaml .Values.frontend_vault_enabled.env | nindent 10 }}
          {{ else }}
          {{- toYaml .Values.frontend_vault_disabled.env | nindent 10 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.vault_settings.enabled }}
          - name: secrets-store-inline
            mountPath: {{ .Values.secrets_location.secrets_default_path }}
            readOnly: true
          {{- end }}
      volumes:
      {{- if .Values.vault_settings.enabled }}
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.csi.csi_default_name }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
