# Default values for deps-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Secrets declaration
# Precreate them before deploying
#kubectl create secret generic frontend-secret \
# --from-literal=file-storage-external-url='<FRONTEND_URL/api/v1/storage/file>' \
# --from-literal=backend-url='<FRONTEND_URL/api>' \
# --from-literal=tables-url='<FRONTEND_URL/api/tables>' \
# --from-literal=ocr-url='<FRONTEND_URL/api/ocr>' \
# --from-literal=keycloak-url='<KEYCLOAK_URL/auth/realms/"name-realm-auth-keycloak">' \

secrets:
  frontend_secret:
    secretName: frontend-secret
  deps_frontend:
    secretName: deps-frontend

helm_logs_job:
  serviceAccountName: gitlab-ci
  image:
    path: "/base/kubernetes-helm"
    pullPolicy: IfNotPresent
    tag: "0.1.1"
  resources: {}

replicaCount: 1

registry: ""
env: ""

image:
  path: /deps-dev-x01/deps-frontend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: artifactory
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  # securityContext: {}
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 1000
  # capabilities:
  #   drop:
  #   - ALL


service:
  type: ClusterIP
  port: 8000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 100Mi
  # requests:
  #   cpu: 80m
  #   memory: 50Mi

frontend_settings:
  FALLBACK_LANG: 'en-US'
  FEATURE_DATA_EXTRACTION: true
  FEATURE_DOCUMENT_CHANGE_TYPE: true
  FEATURE_DOCUMENT_DELETE: true
  FEATURE_DOCUMENT_UPLOAD: true
  FEATURE_ENTITIES_UPLOAD: true
  FEATURE_INVITE_OPTIONS: true
  FEATURE_LABELING_TOOL: true
  FEATURE_LIST_EDITING_MODE: true
  FEATURE_MACHINE_LEARNING_MODELS: true
  FEATURE_RETRY_PREVIOUS_STEP: true
  FEATURE_BULK_RETRY_PREVIOUS_STEP: true
  FEATURE_RUN_PIPELINE: true
  FEATURE_TABLE_DETECTION: true
  FEATURE_USER_MANAGEMENT: true
  FEATURE_INVITE_BY_MAIL: true
  FEATURE_COPY_INVITE: true
  FEATURE_PAGINATED_TABLES: true
  FEATURE_CONFIGURABLE_CONFIDENCE_LEVEL: true
  FEATURE_CONFIDENCE_LEVEL_VIEW: 'asNumbers'
  FEATURE_MANAGE_TEMPLATE_VERSIONS: false
  DEFAULT_CONFIDENCE_LEVEL_TO_DISPLAY: 'high,medium,low,notApplicable'
  FEATURE_HIDE_LOW_CONFIDENCE_DUE_TO_VALIDATION_ERRORS: false
  FEATURE_SHOW_NOT_APPLICABLE_CONFIDENCE: false
  FEATURE_COLLAPSIBLE_SELECTED_CELLS: false
  FEATURE_TRIAL_VERSION: false
  FEATURE_UI_SETTINGS: true
  FEATURE_OIDC_LOG_LEVEL: 2
  FEATURE_SERVER_SENT_EVENTS: false
  FEATURE_OCR_INTERSECTION_ALGORITHM: true
  FEATURE_OCR_INTERSECTION_ALGORITHM_THRESHOLD: 0.5
  FEATURE_AUTO_LABELING: false
  FEATURE_DASHBOARD: true
  FEATURE_OUTPUT_PROFILES: true
  FEATURE_LLM_EXTRACTORS: true
  FEATURE_HIDDEN_ENGINES: ''
  MENU_INTEGRATION_SCRIPT_URI: ''
  FEATURE_HIDDEN_LLM_PROVIDERS: ''
  FEATURE_TEMPLATES: true
  FEATURE_PROTOTYPES: true
  FEATURE_PROTOTYPE_REFERENCE_LAYOUT: true
  FEATURE_DOCUMENT_LAYOUT_EDITING: true
  FEATURE_AI_PROMPTED_EXTRACTORS: true
  FEATURE_FILE_LAYOUT_EDITING: false
  FEATURE_DOCUMENT_LAYOUT: true
  FEATURE_FILL_CANVAS_POLYGONS: false
  FEATURE_MULTIFILE_SESSION_UPLOAD: false
  FEATURE_SCALE_TO_POINT: false
  FEATURE_HIDE_LEGACY: true
  FEATURE_GEN_AI_CHAT: true
  FEATURE_AGENTIC_DOCUMENT_PROCESSING: true
  FEATURE_GEN_AI_KEY_VALUE_FIELDS: false
  FEATURE_SEQUENTIAL_PROTOTYPE_REQUESTS: true
  FEATURE_FILE_CACHE: true
  FEATURE_PDF_VIEWER: true
  FEATURE_PER_FIELD_VALIDATION: true
  FEATURE_FIELDS_DISPLAY_MODE: true
  FEATURE_ENRICHMENT: true
  FEATURE_LLM_DATA_EXTRACTION: true
  FEATURE_CONSOLIDATED_DOCUMENT_TYPE_FIELDS: false
  FEATURE_DOCUMENT_TYPES_GROUPS: true
  FEATURE_FILES_BATCH: true
  FEATURE_AZURE_CLOUD_NATIVE_EXTRACTOR: true
  FEATURE_CLASSIFIER: true
  FEATURE_OMR_AREA: true
  FEATURE_PDF_SPLITTING: true
  FEATURE_ASSIGN_DOCUMENT_TYPE_TO_FILE: true
  FEATURE_FILES: true
  FEATURE_DOCUMENT_TYPE_IMPORT_EXPORT: true
  FEATURE_SERVICE_AVAILABILITY_CHECK: true
  FEATURE_VALIDATION_BUSINESS_RULES: true
  FEATURE_PROMPT_CALIBRATION_STUDIO: true
  FEATURE_PROMPT_CALIBRATION_STUDIO_MODEL: 'dial@openai.gpt-4-omni-mini-text'
  FEATURE_PROMPT_CALIBRATION_STUDIO_TOP_P: 1
  FEATURE_PROMPT_CALIBRATION_STUDIO_TEMPERATURE: 0
  FEATURE_PROMPT_CALIBRATION_STUDIO_GROUPING_FACTOR: 5
  DEFAULT_MAX_CELL_CONTENT_LENGTH: 12
  ELASTIC_ENVIRONMENT: ''
  ELASTIC_SERVICE_NAME: ''
  ELASTIC_PROJECT_CODE: ''
  MAX_FILE_SIZE_MB: 100
  REQUEST_TIMEOUT: 2400000
  MAX_PROTOTYPE_REFERENCE_LAYOUT_SIZE_MB: 100
  WTF_CSRF_ENABLED: true
  AUTH_SCOPE: ''
  GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL: ''
  ONE_DRIVE_SERVICE_ACCOUNT_EMAIL: ''
  api_gateway_url: 'api/deps'
  backend_url: 'api/document'
  comparison_url: 'api/comparison'
  file_storage_url: 'api/storage'
  iam_url: 'api/iam'
  ocr_url: 'api/ocr'
  omr_url: 'api/omr'
  preprocess_url: 'api/preprocess'
  tables_url: 'api/tables'
  template_url: 'api/template'
  workflow_manager_url: 'api/workflow-manager'
  output_exporting_url: 'api/output-exporting'
  image_preprocess_url: 'api/image-preprocess'
  document_type_url: 'api/document-type'
  extraction_url: 'api/extraction'
  unifier_url: 'api/unifier'
  result_exporting_url: 'api/result-exporting'
  prototype_url: 'api/prototype'
  ner_url: 'api/ner'
  prompter_url: 'api/prompter'
  base_api_url: 'api'
  agentic_ai_url: 'api/agentic-ai'

nodeSelector: {}

tolerations: []

affinity: {}

settings: {}

helm:
  helm_logs_job_enabled: false

csi:
  csi_default_name: deps-frontend
  vault_namespace: 'k8s-dev'
  roleName: 'k8s-dev'
  vaultKubernetesMountPath: 'kubernetes-dev'

secrets_location:
  secrets_default_path: "/mnt/secrets-store"

service_account:
  serviceAccountName: 'deps-develop'

azure_kv_settings:
  keyvaultName: ""
  tenantId: ""
  userAssignedIdentityID: ""
  resourceGroup: ""
  subscriptionId: ""

vault_settings:
  enabled: false
  hashicorp_vault: false
  azure_key_vault: false
  gcp_secret_manager: false
  aws_secret_manager: false
  aws_secret_manager_region: ''

frontend_vault_enabled:
  env:
  - name: AUTH_TYPE
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: auth-type
  - name: AUTH_REALM
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: auth-realm
  - name: AUTH_BASE_URL
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: auth-base-url
  - name: AUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: auth-client-id
  - name: SUPPORT_EMAIL
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: support-email
  - name: ELASTIC_SERVER_URL
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: elastic-server-url
  - name: GOOGLE_DRIVE_API_KEY
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: google-drive-api-key
  - name: GOOGLE_DRIVE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: google-drive-client-id
  - name: ONE_DRIVE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: one-drive-client-id
  - name: MFE_COMPARISON_URL
    valueFrom:
      secretKeyRef:
        name: deps-frontend
        key: mfe-comparison-url

frontend_vault_disabled:
  env:
  - name: AUTH_TYPE
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: auth-type
  - name: AUTH_REALM
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: auth-realm
  - name: AUTH_BASE_URL
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: auth-base-url
  - name: AUTH_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: auth-client-id
  - name: SUPPORT_EMAIL
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: support-email
  - name: ELASTIC_SERVER_URL
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: elastic-server-url
  - name: GOOGLE_DRIVE_API_KEY
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: google-drive-api-key
  - name: GOOGLE_DRIVE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: google-drive-client-id
  - name: ONE_DRIVE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: frontend-secret
        key: one-drive-client-id
  - name: MFE_COMPARISON_URL
    valueFrom:
      secretKeyRef:
        name: frontend-custom-url
        key: mfe-comparison-url
