include:
  - project: 'epm-deps/deps-pipelines'
    ref: 0.8.6
    file: '/shared/python.gitlab-ci.yml'
  - local: '/frontend.gitlab-ci.yml'


stages:
  - build
  - tests
  - post-tests
  - deploy

.node_modules-cache: &node_modules-cache
  key:
    files:
      - yarn.lock
  paths:
    - node_modules
  policy: pull

.yarn-cache: &yarn-cache
  key: yarn-$CI_COMMIT_REF_SLUG
  paths:
    - .yarn-cache

.test-cache: &test-cache
  key: test-$CI_COMMIT_REF_SLUG
  paths:
    - .jestcache
  policy: pull-push

lint:
  stage: tests
  interruptible: true
  extends:
    - .verification-defaults
  before_script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
  script:
    - yarn lint
  cache:
    - <<: *yarn-cache


ci:
  parallel:
    matrix:
      - SHARD: [1, 2, 3, 4, 5]
  variables:
    GIT_SUBMODULE_STRATEGY: "normal"
  stage: tests
  interruptible: true
  extends:
    - .verification-defaults
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
    - yarn test:ci --shard=${SHARD}/$CI_NODE_TOTAL --cacheDirectory=.jestcache
    - mv coverage/coverage-final.json coverage/$CI_NODE_INDEX.json
  when: on_success
  allow_failure: false
  artifacts:
    when: always
    name: coverage-frontend
    paths:
      - coverage/
      - junit.xml
    reports:
      junit:
        - junit.xml
  needs: ["build"]
  cache:
    - <<: *node_modules-cache
    - <<: *test-cache
    - <<: *yarn-cache

report-coverage:
  stage: post-tests
  interruptible: true
  variables:
    GIT_SUBMODULE_STRATEGY: "normal"
  extends:
    - .verification-defaults
  before_script: |
    if [[ $CI_PIPELINE_SOURCE == "merge_request_event" ]] || [[ $CI_COMMIT_BRANCH == $DEPLOY_DEV_BRANCH ]] || [[ $CI_COMMIT_BRANCH == $DEPLOY_RELEASE_BRANCH ]]; then
      yarn install --frozen-lockfile --cache-folder .yarn-cache --prefer-offline
    else
      echo "No test"
    fi
  script: |
    if [[ $CI_PIPELINE_SOURCE == "merge_request_event" ]] || [[ $CI_COMMIT_BRANCH == $DEPLOY_DEV_BRANCH ]] || [[ $CI_COMMIT_BRANCH == $DEPLOY_RELEASE_BRANCH ]]; then
      yarn nyc merge coverage/ coverage/final.json --nycrc-path ./config/nyc.config.js
      yarn nyc report -t coverage --check-coverage --nycrc-path ./config/nyc.config.js
    else
      echo "No test"
    fi
  artifacts:
    name: coverage-frontend
    paths:
      - coverage/
  needs: ["ci"]
  cache:
    - <<: *node_modules-cache
    - <<: *yarn-cache

helmlint:
  script:
    - helm lint .helm/services
    - helm template $CI_PROJECT_NAME .helm/services --output-dir chart
