
const DOCUMENT_LAYOUT_FEATURE = {
  KEY_VALUE_PAIRS: 'kvps',
  TABLES: 'tables',
  TEXT: 'text',
  IMAGES: 'images',
}

const DOCUMENT_LAYOUT_TYPE = {
  TABLES: 'tables',
  KEY_VALUE_PAIRS: 'keyValuePairs',
  PARAGRAPHS: 'paragraphs',
  IMAGES: 'images',
}

const DOCUMENT_LAYOUT_PARSING_TYPE = {
  TESSERACT: 'TESSERACT',
  GCP_VISION: 'GCP_VISION',
  AZURE_FORM_RECOGNIZER: 'AZURE_FORM_RECOGNIZER',
  AWS_TEXTRACT: 'AWS_TEXTRACT',
  DOCX: 'DOCX',
  USER_DEFINED: 'USER_DEFINED',
}

const DOCUMENT_LAYOUT_FEATURE_TO_LAYOUT_TYPE = {
  [DOCUMENT_LAYOUT_FEATURE.TEXT]: DOCUMENT_LAYOUT_TYPE.PARAGRAPHS,
  [DOCUMENT_LAYOUT_FEATURE.TABLES]: DOCUMENT_LAYOUT_TYPE.TABLES,
  [DOCUMENT_LAYOUT_FEATURE.KEY_VALUE_PAIRS]: DOCUMENT_LAYOUT_TYPE.KEY_VALUE_PAIRS,
  [DOCUMENT_LAYOUT_FEATURE.IMAGES]: DOCUMENT_LAYOUT_TYPE.IMAGES,
}

export {
  DOCUMENT_LAYOUT_FEATURE,
  DOCUMENT_LAYOUT_TYPE,
  DOCUMENT_LAYOUT_PARSING_TYPE,
  DOCUMENT_LAYOUT_FEATURE_TO_LAYOUT_TYPE,
}
