
const FileExtension = {
  JPG: '.jpg',
  JPEG: '.jpeg',
  PNG: '.png',
  PDF: '.pdf',
  XML: '.xml',
  JSON: '.json',
  MSG: '.msg',
  EML: '.eml',
  XLSX: '.xlsx',
  XLS: '.xls',
  XLSM: '.xlsm',
  XLTX: '.xltx',
  XLTM: '.xltm',
  ZIP: '.zip',
  DOCX: '.docx',
  CSV: '.csv',
  TIFF: '.tiff',
  TIF: '.tif',
}

const RESOURCE_FILE_EXTENSION_JPG = 'JPG'
const RESOURCE_FILE_EXTENSION_JPEG = 'JPEG'
const RESOURCE_FILE_EXTENSION_PNG = 'PNG'
const RESOURCE_FILE_EXTENSION_PDF = 'PDF'
const RESOURCE_FILE_EXTENSION_XML = 'XML'
const RESOURCE_FILE_EXTENSION_JSON = 'JSON'
const RESOURCE_FILE_EXTENSION_MSG = 'MSG'
const RESOURCE_FILE_EXTENSION_EML = 'EML'
const RESOURCE_FILE_EXTENSION_XLSX = 'XLSX'
const RESOURCE_FILE_EXTENSION_XLS = 'XLS'
const RESOURCE_FILE_EXTENSION_XLSM = 'XLSM'
const RESOURCE_FILE_EXTENSION_XLTX = 'XLTX'
const RESOURCE_FILE_EXTENSION_XLTM = 'XLTM'
const RESOURCE_FILE_EXTENSION_ZIP = 'ZIP'
const RESOURCE_FILE_EXTENSION_DOCX = 'DOCX'
const RESOURCE_FILE_EXTENSION_CSV = 'CSV'
const RESOURCE_FILE_EXTENSION_TIFF = 'TIFF'

const FILE_EXTENSION_TO_DISPLAY_TEXT = {
  [FileExtension.JPG]: RESOURCE_FILE_EXTENSION_JPG,
  [FileExtension.JPEG]: RESOURCE_FILE_EXTENSION_JPEG,
  [FileExtension.PNG]: RESOURCE_FILE_EXTENSION_PNG,
  [FileExtension.PDF]: RESOURCE_FILE_EXTENSION_PDF,
  [FileExtension.XML]: RESOURCE_FILE_EXTENSION_XML,
  [FileExtension.JSON]: RESOURCE_FILE_EXTENSION_JSON,
  [FileExtension.MSG]: RESOURCE_FILE_EXTENSION_MSG,
  [FileExtension.EML]: RESOURCE_FILE_EXTENSION_EML,
  [FileExtension.XLSX]: RESOURCE_FILE_EXTENSION_XLSX,
  [FileExtension.XLS]: RESOURCE_FILE_EXTENSION_XLS,
  [FileExtension.XLSM]: RESOURCE_FILE_EXTENSION_XLSM,
  [FileExtension.XLTX]: RESOURCE_FILE_EXTENSION_XLTX,
  [FileExtension.XLTM]: RESOURCE_FILE_EXTENSION_XLTM,
  [FileExtension.ZIP]: RESOURCE_FILE_EXTENSION_ZIP,
  [FileExtension.DOCX]: RESOURCE_FILE_EXTENSION_DOCX,
  [FileExtension.CSV]: RESOURCE_FILE_EXTENSION_CSV,
  [FileExtension.TIFF]: RESOURCE_FILE_EXTENSION_TIFF,
  [FileExtension.TIF]: RESOURCE_FILE_EXTENSION_TIFF,
}

const FILE_EXTENSION_TO_DOWNLOAD_FORMAT = {
  [FileExtension.XLSX]: 'excel',
  [FileExtension.JSON]: 'json',
}

export {
  FileExtension,
  FILE_EXTENSION_TO_DISPLAY_TEXT,
  FILE_EXTENSION_TO_DOWNLOAD_FORMAT,
}
