
const CONFIDENCE_BREAKPOINT = {
  LOW: 81,
  MEDIUM: 91,
}

const NOT_APPLICABLE_CONFIDENCE_LEVEL = -1

const MAX_CONFIDENCE_LEVEL = 1

export {
  CONFIDENCE_BREAKPOINT,
  MAX_CONFIDENCE_LEVEL,
  NOT_APPLICABLE_CONFIDENCE_LEVEL,
}
