
const BATCHES_PER_PAGE = 'batchesPerPage'
const POST_SIGN_IN_REDIRECT_URL = 'postSignInRedirectUrl'
const NER_FILTER = 'NERFilter'
const TABLE_FIELD_PAGINATION = 'tableFieldPagination'
const TRIAL_NOTIFICATION_LAST_SHOWN_DATE = 'trialNotificationLastShownDate'
const PAGE_SEPARATOR_POSITION = 'pageSeparatorPosition'
const DOCUMENTS_PER_PAGE = 'documentsPerPage'
const USERS_PER_PAGE = 'usersPerPage'
const DOCUMENT_TYPES_PER_PAGE = 'documentTypesPerPage'
const DOCUMENT_TYPES_GROUPS_PER_PAGE = 'documentTypesGroupsPerPage'
const GROUP_DOCUMENT_TYPES_PER_PAGE = 'groupDocumentTypesPerPage'
const UI_ENV_SETTINGS = 'uiEnvSettings'
const HAS_SEEN_MERGED_CELLS_NOTICE = 'hasSeenMergedCellsNotice'
const HAS_SEEN_NO_TABLE_SELECTED_NOTICE = 'hasSeenNoTableSelectedNotice'
const FILES_PER_PAGE = 'filesPerPage'
const TABLE_COLUMN_WIDTHS = 'tableColumnWidths'
const AGENTIC_CHAT_MODAL_STATE = 'agenticChatModalState'

export {
  BATCHES_PER_PAGE,
  POST_SIGN_IN_REDIRECT_URL,
  NER_FILTER,
  TABLE_FIELD_PAGINATION,
  TRIAL_NOTIFICATION_LAST_SHOWN_DATE,
  PAGE_SEPARATOR_POSITION,
  DOCUMENTS_PER_PAGE,
  USERS_PER_PAGE,
  DOCUMENT_TYPES_PER_PAGE,
  DOCUMENT_TYPES_GROUPS_PER_PAGE,
  GROUP_DOCUMENT_TYPES_PER_PAGE,
  UI_ENV_SETTINGS,
  HAS_SEEN_MERGED_CELLS_NOTICE,
  HAS_SEEN_NO_TABLE_SELECTED_NOTICE,
  FILES_PER_PAGE,
  TABLE_COLUMN_WIDTHS,
  AGENTIC_CHAT_MODAL_STATE,
}
