image:
  path: /deps-presale-x01/deps-frontend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources: {}
  # limits:
  #   cpu:
  #   memory:
  # requests:
  #   cpu:
  #   memory:

settings: {}

helm:
  helm_logs_job_enabled: false

csi:
  vault_namespace: 'k8s-presale'
  roleName: 'k8s-presale'
  vaultKubernetesMountPath: 'kubernetes-presale'

service_account:
  serviceAccountName: 'deps-presale'
