# Default values for deps-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  path: /deps-platform/deps-frontend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources: {}

settings: {}

helm:
  helm_logs_job_enabled: false

frontend_settings:
  FEATURE_GEN_AI_CHAT: true
  FEATURE_CONSOLIDATED_DOCUMENT_TYPE_FIELDS: true

csi:
  vault_namespace: 'k8s-demo'
  roleName: 'k8s-demo'
  vaultKubernetesMountPath: 'kubernetes-demo'

service_account:
  serviceAccountName: 'deps-demo'
